# Change these first
owner: AsurRaa # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: sai-website
    url: https://saicambodianartist.com
  - name: asurraa-website
    url: https://asurraa.com
  - name: thakvika-api
    url: https://thakvika-api-dev.asurraa.com
  - name: thakvika-website
    url: https://thakvika.asurraa.com
  - name: lv - website
    url: https://lauvann.info/

status-website:
  # cname: status.asurraa.com
  logoUrl: https://nest.land/images/nest.land/favicon_light.svg
  name: Nest Status Page
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  uptime: "*/5 * * * *"
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 0 * * *"
  staticSite: "0 0 * * *"
  updates: "0 0 * * *"
